export const dashboardUiCopyTables = {
  wbTableRows: "Строк WB",
  yes: "да",
  no: "нет",
  productsTable: "Таблица товаров",
  searchTextTable: "Таблица поисковых фраз",
  selectProduct: "Выберите товар в таблице, чтобы увидеть его поисковые фразы.",
  noProducts: "В выбранной выгрузке нет товаров.",
  noQueries: "Для выбранного товара WB не вернул поисковые фразы.",
  product: "Товар",
  brand: "Бренд",
  subject: "Предмет",
  vendorCode: "Артикул",
  frequency: "Частота",
  weekFrequency: "Частота за неделю",
  avgPosition: "Средняя позиция",
  orders: "Заказанные товары, шт",
  openCard: "Открытия карточки",
  clicksCount: "Количество кликов",
  ctr: "CTR",
  addToCart: "Добавления в корзину",
  ctc: "CTC",
  cto: "CTO",
  clickToOrder: "Клик-заказ",
  wbCluster: "Кластер WB",
  weight: "Вес",
  openToCart: "Конверсия в корзину",
  visibility: "Видимость",
  rowNumber: "№",
  productIdColumn: "ID товара",
  productNameColumn: "Название товара",
} as const;
