export const dashboardUiCopyShell = {
  badge: "Платформа автоматизации WB",
  title: "Управление выгрузками Wildberries",
  subtitle:
    "Список методов выгрузки, таймер повторного запуска и отдельный рабочий лист для деталей каждой выгрузки.",
  viewExports: "Выгрузки",
  viewMethod: "Лист метода",
  viewProducts: "Реклама",
  viewCatalogProducts: "Товары",
  viewUnitEconomics: "Юнит Экономика",
  viewJam: "JAM",
  viewToken: "Токен",
  refresh: "Обновить",
  backendStatus: "Статус backend",
  integrationReady: "Интеграция",
  tokenStatus: "Токен",
  methodsCount: "Методов",
  online: "онлайн",
  offline: "офлайн",
  ready: "готово",
  notReady: "не готово",
  connected: "подключен",
  notSet: "не задан",
  tokenTitle: "Сессия токена WB API",
  tokenText:
    "Токен сохраняется на backend в записываемый env-файл, не уходит в git и переживает перезапуски backend.",
  tokenPlaceholder: "Вставьте токен Analytics",
  saveToken: "Сохранить токен",
  savingToken: "Сохраняем...",
  clearToken: "Очистить",
  tokenMetaSource: "Источник токена",
  tokenMetaChecked: "Обновлено",
  methodsTitle: "Методы выгрузки",
  methodsText:
    "Каждая карточка открывает отдельный рабочий лист метода с архивом, таймером и таблицами.",
  openMethod: "Открыть лист",
  methodStatus: "Статус метода",
  methodCooldown: "Таймер повторного запуска",
  readyForRun: "готов к запуску",
  canRunNow: "можно запускать сейчас",
  waitUntil: "через",
  lastAttempt: "Последняя попытка",
  lastSuccess: "Последний успех",
  lastError: "Последняя ошибка",
  exportsWorkspace: "Рабочий лист выгрузки",
  productsWorkspace: "Товары",
  workspaceText:
    "В рабочем поле видны архив метода, статус лимита и табличный просмотр данных.",
  backToMethods: "Назад к методам",
  runExport: "Запустить выгрузку",
  runningExport: "Выгружаем...",
  exportQueuedTitle: "Выгрузка поставлена в очередь",
  exportRunningTitle: "Выгрузка выполняется",
  exportFailedTitle: "Выгрузка завершилась ошибкой",
  exportCompletedTitle: "Выгрузка завершена",
  exportQueuedMessage: "WB-выгрузка уже принята backend и выполняется в фоне.",
  exportRunningMessage: "Backend обрабатывает выгрузку в фоне. Экран можно не держать открытым.",
  exportFailedMessage: "Backend не смог завершить выгрузку. Запустите ее повторно после исправления причины.",
  exportCompletedMessage: "Готовый архив уже сохранен и доступен в рабочем листе метода.",
  methodArchive: "Архив метода",
  archiveEmpty: "По этому методу пока нет успешных выгрузок.",
  exportSummary: "Сводка выгрузки",
  selectedExport: "Выбранная выгрузка",
  period: "Период",
  createdAt: "Создана",
  rawArchive: "Архив raw-ответов",
  wbRawTables: "WB поля без изменений",
  wbRawHint:
    "Ниже показан полный набор полей WB из ответа API, без урезания и без домыслов.",
  columnOrderHint: "Зажмите шапку столбика за знак из двух полосок и тяните в нужное место.",
  resetColumns: "Сбросить порядок",
  loading: "Загружаем...",
  backendError: "Не удалось загрузить состояние панели.",
  tokenError: "Не удалось сохранить токен WB API.",
  exportError: "Не удалось выполнить выгрузку из WB API.",
  tokenSaved: "Токен сохранен в backend.",
  tokenCleared: "Токен очищен из backend.",
  hiddenBrokenData: "[поврежденная строка скрыта]",
  runtimeSource: "runtime-поле панели",
  envSource: ".env backend",
  missingSource: "токен отсутствует",
  fixedProductsCount: "Уникальных товаров",
  productsSearchPlaceholder: "Поиск по названию или ID товара",
  exportSearchPlaceholder: "Поиск по названию товара в выгрузке",
} as const;
