export const dashboardUiCopyAdvertising = {
  advertId: "ID рекламы",
  campaign: "Кампания",
  status: "Статус",
  source: "Источник",
  views: "Показы",
  shks: "Шт.",
  bid: "Ставка",
  cpc: "CPC",
  cpm: "CPM",
  cpo: "СРО",
  spend: "Расход",
  viewToOrder: "Показ-заказ",
  jamQueries: "Джем: запросы",
  jamFrequency: "Джем: частотность",
  jamClicks: "Джем: клики",
  jamAddToCart: "Джем: корзины",
  jamOrders: "Джем: заказы",
  jamAvgPosition: "Джем: ср. позиция",
  jamCtc: "Джем: конв. в корзину",
  jamCto: "Джем: конв. в заказ",
  dailyStats: "Дневная статистика",
  minusPhrases: "Минус-фразы",
  keywordStats: "Ключевые слова",
  date: "Дата",
  phrase: "Фраза",
  keyword: "Ключевое слово",
  syncAdvertising: "Синхронизировать рекламу",
  advertisingSyncStarted:
    "Синхронизация рекламы запущена. Данные будут обновляться партиями с учетом лимитов WB Promotion API.",
  advertisingSyncError: "Не удалось запустить синхронизацию рекламы WB Promotion API.",
  advertisingLiveRefreshing: "Обновляем данные товара напрямую из WB Promotion API...",
  advertisingLiveUpdated: "Данные товара обновлены по WB Promotion API.",
  refreshProductAdvertising: "Обновить данные",
  advertisingBidSaveError: "Не удалось применить ставку на WB.",
  advertisingClusterActionError: "Не удалось изменить статус кластера на WB.",
  productAdvertisingWorkspaceLoadError: "Не удалось загрузить рабочую область товара.",
  productAdvertisingClusterTableLoadError:
    "Не удалось загрузить таблицу кластеров товара.",
  productAdvertisingClusterQueriesLoadError: "Не удалось загрузить запросы кластера.",
  productAdvertisingPrefetchError: "Не удалось заранее подготовить рекламные снимки товара.",
  productAdvertisingBackgroundPrefetchError:
    "Не удалось заранее подготовить фоновые рекламные снимки товара.",
  productAdvertisingSinglePrefetchError:
    "Не удалось заранее подготовить рекламный снимок товара.",
  advertisingBidSaving: "Сохраняем...",
  clusterSearchPlaceholder: "Поиск по кластерам",
  allClusters: "Все",
  activeClusters: "Активные",
  excludedClusters: "Исключенные",
  statsClusters: "Только статистика",
  withBidOnly: "Со ставкой",
  withSpendOnly: "С расходом",
  sortBySpend: "Сортировка: расход",
  sortByOrders: "Сортировка: заказы",
  sortByClicks: "Сортировка: клики",
  sortByBid: "Сортировка: ставка",
  activeCount: "Активных",
  excludedCount: "Исключенных",
  totalSpend: "Общий расход",
  totalOrders: "Всего заказов",
  clusterBoardTitle: "Рекламные кампании товара",
  clusterBoardText:
    "Сначала посмотрите, сколько у товара рекламных кампаний и в каком они статусе. Затем выберите кампанию и проваливайтесь в ее кластеры и статистику.",
  campaignOverviewTitle: "Список кампаний товара",
  campaignOverviewText:
    "Здесь видны найденные рекламные кампании товара, их текущий статус и краткая сводка по кластерам.",
  tablePage: "Страница",
  previousPage: "Назад",
  nextPage: "Далее",
  campaignDetailsTitle: "Детали выбранной кампании",
  campaignDetailsText:
    "После выбора кампании ниже открываются ее кластеры, дневная статистика, минус-фразы и ключевые слова.",
  inactiveCampaigns: "Неактивных РК",
  wbStatus: "Статус WB",
  campaignInventoryMissing:
    "По этому товару пока не найдена связка с рекламными кампаниями в локальном инвентаре WB Promotion API. Поэтому список РК и статистика еще пустые.",
  noCampaignDetails: "По выбранной кампании пока нет детализированных кластеров или статистики.",
  workspaceRefreshing: "Обновляем данные без сброса экрана.",
  clusterTableRefreshing: "Обновляем строки без сброса таблицы.",
  noClustersForFilter: "По выбранному фильтру кластеры не найдены.",
  noClustersForCampaign: "По выбранной кампании нет кластеров за указанный период.",
} as const;
